# modified copy of:
# https://github.com/marimo-team/marimo-gh-pages-template/blob/main/.github/workflows/deploy.yml
# https://github.com/jeertmans/manim-slides-starter/blob/main/.github/workflows/deploy_pages.yml

name: Deploy Marimo and Manim to GH-pages on https://github.com/ny-x4/nyxtudes

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch repository to ny-x4/nyxtudes via gh-workflow
        run:  gh workflow run --repo ny-x4/nyxtudes 'deploy.yml'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
